import type {
  AttentionItem,
  BranchItem,
  CampaignSpace,
  Department,
  DepartmentId,
  Member,
} from "./types";

export const PRODUCT_NAME = "Workbench";

export const spaces: CampaignSpace[] = [
  {
    id: "secureedge",
    name: "SecureEdge Enterprise Launch",
    client: "Northwind Security",
    launchDate: "Nov 10",
    stage: "Localization",
    attention: 2,
    blockers: 2,
    status: "blocked",
  },
  {
    id: "nova",
    name: "Nova AI Product Narrative",
    client: "Nova Labs",
    launchDate: "Nov 18",
    stage: "Creative",
    attention: 1,
    blockers: 0,
    status: "in_progress",
  },
  {
    id: "atlas",
    name: "Atlas Platform Refresh",
    client: "Atlas Cloud",
    launchDate: "Nov 7",
    stage: "Launch",
    attention: 0,
    blockers: 0,
    status: "ready",
  },
];

/** Team roster — agents and humans are the same kind of member. */
export const members: Member[] = [
  {
    id: "m-maya",
    name: "Maya Chen",
    role: "Campaign ops",
    kind: "human",
    initials: "MC",
    status: "online",
    departmentIds: ["planning", "approvals", "launch"],
  },
  {
    id: "m-sarah",
    name: "Sarah Okonkwo",
    role: "Legal",
    kind: "human",
    initials: "SO",
    status: "working",
    departmentIds: ["compliance", "approvals"],
  },
  {
    id: "m-jonas",
    name: "Jonas Reed",
    role: "Brand",
    kind: "human",
    initials: "JR",
    status: "away",
    departmentIds: ["brand", "creative"],
  },
  {
    id: "m-orchestrator",
    name: "Campaign Manager",
    role: "Orchestration",
    kind: "agent",
    initials: "CM",
    status: "working",
    departmentIds: ["intake", "planning", "launch"],
  },
  {
    id: "m-research",
    name: "Research",
    role: "Insights",
    kind: "agent",
    initials: "RS",
    status: "online",
    departmentIds: ["research", "strategy"],
  },
  {
    id: "m-strategy",
    name: "Strategy",
    role: "Positioning",
    kind: "agent",
    initials: "ST",
    status: "online",
    departmentIds: ["strategy"],
  },
  {
    id: "m-creative",
    name: "Creative",
    role: "Production",
    kind: "agent",
    initials: "CR",
    status: "online",
    departmentIds: ["creative"],
  },
  {
    id: "m-brand",
    name: "Brand Guardian",
    role: "Brand QA",
    kind: "agent",
    initials: "BG",
    status: "online",
    departmentIds: ["brand"],
  },
  {
    id: "m-compliance",
    name: "Compliance",
    role: "Claims & policy",
    kind: "agent",
    initials: "CP",
    status: "working",
    departmentIds: ["compliance"],
  },
  {
    id: "m-l10n",
    name: "Localization",
    role: "Markets",
    kind: "agent",
    initials: "LZ",
    status: "working",
    departmentIds: ["localization"],
  },
];

export const departments: Department[] = [
  {
    id: "intake",
    name: "Intake",
    summary: "Brief parsed · objectives locked",
    status: "complete",
    tone: "ok",
    memberIds: ["m-maya", "m-orchestrator"],
    dependsOn: [],
  },
  {
    id: "planning",
    name: "Planning",
    summary: "Workflow + ownership set",
    status: "complete",
    tone: "ok",
    memberIds: ["m-maya", "m-orchestrator"],
    dependsOn: ["intake"],
  },
  {
    id: "research",
    name: "Research",
    summary: "ICP + competitive notes ready",
    status: "complete",
    tone: "ok",
    memberIds: ["m-research"],
    dependsOn: ["planning"],
  },
  {
    id: "strategy",
    name: "Strategy",
    summary: "Messaging pillars approved",
    status: "complete",
    tone: "ok",
    memberIds: ["m-strategy", "m-research"],
    dependsOn: ["research"],
  },
  {
    id: "creative",
    name: "Creative",
    summary: "24 assets across 4 channels",
    status: "in_review",
    tone: "warn",
    memberIds: ["m-creative", "m-jonas"],
    dependsOn: ["strategy"],
    branches: [
      { id: "linkedin", name: "LinkedIn", status: "blocked", tone: "danger" },
      { id: "email", name: "Email", status: "complete", tone: "ok" },
      { id: "landing", name: "Landing", status: "complete", tone: "ok" },
      { id: "search", name: "Search", status: "in_progress", tone: "info" },
    ],
    attention: "LinkedIn Ad #3 waiting on legal",
  },
  {
    id: "brand",
    name: "Brand",
    summary: "Voice + terminology checks",
    status: "complete",
    tone: "ok",
    memberIds: ["m-brand", "m-jonas"],
    dependsOn: ["creative"],
  },
  {
    id: "compliance",
    name: "Legal & Compliance",
    summary: "1 unsupported claim open",
    status: "blocked",
    tone: "danger",
    memberIds: ["m-compliance", "m-sarah"],
    dependsOn: ["brand"],
    attention: "Sarah reviewing claim replacement",
  },
  {
    id: "localization",
    name: "Localization",
    summary: "US ready · UK review · DE blocked",
    status: "blocked",
    tone: "danger",
    memberIds: ["m-l10n", "m-sarah"],
    dependsOn: ["compliance"],
    branches: [
      { id: "us", name: "United States", status: "ready", tone: "ok" },
      { id: "uk", name: "United Kingdom", status: "in_review", tone: "warn" },
      { id: "de", name: "Germany", status: "blocked", tone: "danger" },
    ],
    attention: "Germany disclaimer missing",
  },
  {
    id: "approvals",
    name: "Approvals",
    summary: "Brand done · Legal pending · Client queued",
    status: "in_review",
    tone: "warn",
    memberIds: ["m-maya", "m-sarah", "m-jonas"],
    dependsOn: ["localization"],
  },
  {
    id: "launch",
    name: "Launch",
    summary: "87 / 100 · 2 blockers remain",
    status: "blocked",
    tone: "warn",
    memberIds: ["m-maya", "m-orchestrator"],
    dependsOn: ["approvals"],
  },
];

export const attentionQueue: AttentionItem[] = [
  {
    id: "att-1",
    campaignId: "secureedge",
    campaignName: "SecureEdge",
    departmentId: "compliance",
    title: "Legal decision needed",
    reason: "Unsupported claim on LinkedIn Ad #3",
    tone: "danger",
    kind: "review",
  },
  {
    id: "att-2",
    campaignId: "secureedge",
    campaignName: "SecureEdge",
    departmentId: "localization",
    title: "Germany blocked",
    reason: "Market disclaimer missing",
    tone: "warn",
    kind: "blocker",
  },
  {
    id: "att-3",
    campaignId: "nova",
    campaignName: "Nova AI",
    departmentId: "strategy",
    title: "Messaging direction",
    reason: "Strategist decision on ICP wording",
    tone: "info",
    kind: "decision",
  },
];

export const issueDetail = {
  title: "Unsupported claim",
  severity: "High risk",
  quote: "Eliminates 100% of security threats.",
  why: "This claim does not exist in the approved claims library.",
  suggestion: "Helps organizations detect and respond to security threats faster.",
  source: "Approved Claims v2.1",
};

/** Overview graph layout positions */
export const departmentLayout: Record<DepartmentId, { x: number; y: number }> = {
  intake: { x: 80, y: 280 },
  planning: { x: 340, y: 280 },
  research: { x: 600, y: 160 },
  strategy: { x: 600, y: 400 },
  creative: { x: 900, y: 280 },
  brand: { x: 1200, y: 160 },
  compliance: { x: 1200, y: 400 },
  localization: { x: 1500, y: 280 },
  approvals: { x: 1800, y: 280 },
  launch: { x: 2100, y: 280 },
};

export const departmentEdges: [DepartmentId, DepartmentId][] = [
  ["intake", "planning"],
  ["planning", "research"],
  ["planning", "strategy"],
  ["research", "creative"],
  ["strategy", "creative"],
  ["creative", "brand"],
  ["creative", "compliance"],
  ["brand", "localization"],
  ["compliance", "localization"],
  ["localization", "approvals"],
  ["approvals", "launch"],
];

/** Per-department branch canvases — work lives here, not “AI tasks”. */
export const branchBoards: Record<DepartmentId, BranchItem[]> = {
  intake: [
    {
      id: "intake-brief",
      kind: "work",
      title: "Client brief",
      body: "Launch SecureEdge across US, UK, DE for CTOs and security leaders.",
      tone: "ok",
      authorId: "m-maya",
      meta: "Complete",
      x: 120,
      y: 140,
    },
    {
      id: "intake-note",
      kind: "note",
      title: "Soft launch Nov 10. Emphasize detection speed, not absolute claims.",
      authorId: "m-maya",
      x: 420,
      y: 180,
    },
    {
      id: "intake-comment",
      kind: "comment",
      title: "Structured the brief into objectives, audiences, and markets.",
      authorId: "m-orchestrator",
      meta: "10:42",
      x: 420,
      y: 320,
    },
  ],
  planning: [
    {
      id: "plan-workflow",
      kind: "instruction",
      title: "Department sequence",
      body: "Research + Strategy in parallel, then Creative, then Brand ‖ Compliance.",
      authorId: "m-orchestrator",
      x: 140,
      y: 160,
    },
    {
      id: "plan-owners",
      kind: "work",
      title: "Ownership map",
      body: "Creative · Jonas · Compliance · Sarah · Markets · Localization",
      tone: "ok",
      meta: "Complete",
      x: 440,
      y: 160,
    },
  ],
  research: [
    {
      id: "res-icp",
      kind: "work",
      title: "ICP brief",
      body: "CTO / CISO / Security Director · enterprise · 500+ seats",
      tone: "ok",
      authorId: "m-research",
      x: 140,
      y: 140,
    },
    {
      id: "res-comp",
      kind: "work",
      title: "Competitive notes",
      body: "Avoid absolute threat-elimination language used by Category C peers.",
      tone: "ok",
      authorId: "m-research",
      x: 420,
      y: 200,
    },
  ],
  strategy: [
    {
      id: "str-msg",
      kind: "work",
      title: "Messaging pillars",
      body: "Detect faster · Reduce SOC load · Governed response",
      tone: "ok",
      authorId: "m-strategy",
      x: 160,
      y: 160,
    },
    {
      id: "str-note",
      kind: "note",
      title: "Keep CTA to demo request, not free trial.",
      authorId: "m-maya",
      x: 460,
      y: 220,
    },
  ],
  creative: [
    {
      id: "cr-li3",
      kind: "asset",
      title: "LinkedIn Ad #3",
      body: "Paid social · English",
      tone: "danger",
      authorId: "m-creative",
      meta: "Needs legal",
      x: 120,
      y: 80,
    },
    {
      id: "cr-email",
      kind: "asset",
      title: "Launch Email",
      body: "Nurture · English",
      tone: "ok",
      authorId: "m-creative",
      meta: "Passed brand",
      x: 120,
      y: 280,
    },
    {
      id: "cr-lp",
      kind: "asset",
      title: "Hero Landing Page",
      body: "Web · English",
      tone: "ok",
      authorId: "m-creative",
      meta: "Passed brand",
      x: 120,
      y: 480,
    },
    {
      id: "cr-instruction",
      kind: "instruction",
      title: "Creative direction",
      body: "Calm enterprise tone. No fear-mongering. Show SOC workflow, not cartoon locks.",
      authorId: "m-jonas",
      x: 420,
      y: 100,
    },
    {
      id: "cr-comment",
      kind: "comment",
      title: "Generated channel pack from strategy pillars. Flagged Ad #3 for claims review.",
      authorId: "m-creative",
      meta: "10:44",
      x: 420,
      y: 280,
    },
    {
      id: "cr-blocker",
      kind: "blocker",
      title: "LinkedIn Ad #3 blocked",
      body: "Waiting on Legal & Compliance before channel can ship.",
      tone: "danger",
      authorId: "m-compliance",
      x: 420,
      y: 420,
    },
  ],
  brand: [
    {
      id: "br-check",
      kind: "work",
      title: "Brand pass",
      body: "87 rules checked · 2 soft fixes applied by Creative",
      tone: "ok",
      authorId: "m-brand",
      x: 160,
      y: 160,
    },
    {
      id: "br-comment",
      kind: "comment",
      title: "Terminology looks good after the SOC-efficiency rewrite.",
      authorId: "m-jonas",
      meta: "10:50",
      x: 440,
      y: 200,
    },
  ],
  compliance: [
    {
      id: "co-claim",
      kind: "blocker",
      title: "Unsupported claim",
      body: "“Eliminates 100% of security threats.” — not in Approved Claims v2.1",
      tone: "danger",
      authorId: "m-compliance",
      x: 140,
      y: 120,
    },
    {
      id: "co-suggest",
      kind: "work",
      title: "Suggested replacement",
      body: "Helps organizations detect and respond to security threats faster.",
      tone: "info",
      authorId: "m-compliance",
      meta: "Awaiting Sarah",
      x: 140,
      y: 320,
    },
    {
      id: "co-comment",
      kind: "comment",
      title: "Please replace the absolute claim before client review.",
      authorId: "m-sarah",
      meta: "10:55",
      x: 460,
      y: 160,
    },
    {
      id: "co-instruction",
      kind: "instruction",
      title: "Review rule",
      body: "Any absolute efficacy claim needs an approved-claims match or human legal sign-off.",
      authorId: "m-sarah",
      x: 460,
      y: 320,
    },
  ],
  localization: [
    {
      id: "loc-us",
      kind: "work",
      title: "United States",
      body: "Creative · Brand · Legal complete",
      tone: "ok",
      meta: "Ready",
      x: 120,
      y: 100,
    },
    {
      id: "loc-uk",
      kind: "work",
      title: "United Kingdom",
      body: "Awaiting client approval",
      tone: "warn",
      meta: "In review",
      x: 120,
      y: 280,
    },
    {
      id: "loc-de",
      kind: "work",
      title: "Germany",
      body: "Disclaimer missing · regional approval paused",
      tone: "danger",
      meta: "Blocked",
      x: 120,
      y: 460,
    },
    {
      id: "loc-blocker",
      kind: "blocker",
      title: "Germany disclaimer",
      body: "Required before regional approval can continue.",
      tone: "danger",
      authorId: "m-l10n",
      x: 420,
      y: 420,
    },
    {
      id: "loc-comment",
      kind: "comment",
      title: "Paused DE variants until disclaimer copy is provided.",
      authorId: "m-l10n",
      meta: "10:53",
      x: 420,
      y: 200,
    },
  ],
  approvals: [
    {
      id: "ap-brand",
      kind: "work",
      title: "Brand approval",
      body: "Jonas signed off",
      tone: "ok",
      authorId: "m-jonas",
      x: 140,
      y: 140,
    },
    {
      id: "ap-legal",
      kind: "work",
      title: "Legal approval",
      body: "Blocked on claim replacement",
      tone: "danger",
      authorId: "m-sarah",
      x: 140,
      y: 300,
    },
    {
      id: "ap-client",
      kind: "work",
      title: "Client approval",
      body: "Not started",
      tone: "neutral",
      x: 140,
      y: 460,
    },
  ],
  launch: [
    {
      id: "la-score",
      kind: "work",
      title: "Launch readiness",
      body: "87 / 100",
      tone: "warn",
      authorId: "m-orchestrator",
      meta: "2 blockers",
      x: 160,
      y: 180,
    },
    {
      id: "la-note",
      kind: "note",
      title: "Tracking confirmed for US + UK. DE pending legal copy.",
      authorId: "m-maya",
      x: 440,
      y: 220,
    },
  ],
};

export function getMember(id?: string) {
  if (!id) return undefined;
  return members.find((m) => m.id === id);
}

export function getDepartment(id: DepartmentId) {
  return departments.find((d) => d.id === id)!;
}

export function membersForDepartment(id: DepartmentId) {
  const dept = getDepartment(id);
  return members.filter((m) => dept.memberIds.includes(m.id));
}
