import { MarkerType, type Edge, type Node } from "@xyflow/react";
import type { BoardNodeData } from "./nodes/CanvasNodes";

export const campaignNodes: Node<BoardNodeData>[] = [
  {
    id: "brief",
    type: "brief",
    position: { x: 40, y: 220 },
    data: {
      kind: "brief",
      title: "SecureEdge Enterprise Launch",
      subtitle: "Launch across US, UK and Germany. Target enterprise CTOs and security leaders.",
      meta: "Parsed from client brief · 10:42",
    },
  },
  {
    id: "strategy",
    type: "stage",
    position: { x: 380, y: 80 },
    data: {
      kind: "stage",
      title: "Strategy",
      subtitle: "Positioning + messaging locked",
      tone: "ok",
    },
  },
  {
    id: "creative",
    type: "stage",
    position: { x: 380, y: 200 },
    data: {
      kind: "stage",
      title: "Creative",
      subtitle: "24 assets generated",
      tone: "ok",
    },
  },
  {
    id: "qa",
    type: "stage",
    position: { x: 380, y: 320 },
    data: {
      kind: "stage",
      title: "Brand + Compliance QA",
      subtitle: "3 claim issues found",
      tone: "warn",
    },
  },
  {
    id: "asset-li3",
    type: "asset",
    position: { x: 680, y: 40 },
    data: {
      kind: "asset",
      title: "LinkedIn Ad #3",
      subtitle: "Paid social · English",
      tone: "danger",
    },
  },
  {
    id: "asset-email",
    type: "asset",
    position: { x: 680, y: 220 },
    data: {
      kind: "asset",
      title: "Launch Email",
      subtitle: "Nurture · English",
      tone: "ok",
    },
  },
  {
    id: "asset-lp",
    type: "asset",
    position: { x: 680, y: 400 },
    data: {
      kind: "asset",
      title: "Hero Landing Page",
      subtitle: "Web · English",
      tone: "ok",
    },
  },
  {
    id: "agent-compliance",
    type: "agent",
    position: { x: 960, y: 20 },
    data: {
      kind: "agent",
      title: "Compliance Agent",
      subtitle: "Flagged unsupported claim",
      meta: "Working · now",
      agentStatus: "working",
    },
  },
  {
    id: "comment-legal",
    type: "comment",
    position: { x: 960, y: 180 },
    data: {
      kind: "comment",
      title: "Please replace the absolute claim before client review.",
      subtitle: "Sarah · Legal · 10:55",
    },
  },
  {
    id: "blocker-claim",
    type: "blocker",
    position: { x: 960, y: 320 },
    data: {
      kind: "blocker",
      title: "Unsupported claim",
      subtitle: "Not found in Approved Claims v2.1",
      tone: "danger",
    },
  },
  {
    id: "market-us",
    type: "market",
    position: { x: 1280, y: 80 },
    data: {
      kind: "market",
      title: "United States",
      subtitle: "Creative · Brand · Legal",
      meta: "Ready",
      tone: "ok",
    },
  },
  {
    id: "market-uk",
    type: "market",
    position: { x: 1280, y: 220 },
    data: {
      kind: "market",
      title: "United Kingdom",
      subtitle: "Awaiting client approval",
      meta: "In review",
      tone: "warn",
    },
  },
  {
    id: "market-de",
    type: "market",
    position: { x: 1280, y: 360 },
    data: {
      kind: "market",
      title: "Germany",
      subtitle: "Disclaimer missing",
      meta: "Blocked",
      tone: "danger",
    },
  },
  {
    id: "agent-l10n",
    type: "agent",
    position: { x: 1520, y: 360 },
    data: {
      kind: "agent",
      title: "Localization Agent",
      subtitle: "Paused on DE disclaimer",
      meta: "Waiting · 12m",
      agentStatus: "waiting",
    },
  },
  {
    id: "blocker-de",
    type: "blocker",
    position: { x: 1520, y: 520 },
    data: {
      kind: "blocker",
      title: "Germany disclaimer",
      subtitle: "Required before regional approval",
      tone: "danger",
    },
  },
  {
    id: "note-launch",
    type: "note",
    position: { x: 1280, y: 520 },
    data: {
      kind: "note",
      title: "Tracking pixels confirmed for US + UK. DE pending legal copy.",
    },
  },
  {
    id: "launch",
    type: "launch",
    position: { x: 1780, y: 220 },
    data: {
      kind: "launch",
      title: "Launch readiness",
      subtitle: "87 / 100 · 2 blockers remain",
      tone: "warn",
    },
  },
];

export const campaignEdges: Edge[] = [
  {
    id: "e-brief-strategy",
    source: "brief",
    target: "strategy",
    markerEnd: { type: MarkerType.ArrowClosed, width: 14, height: 14, color: "#d3d1cb" },
  },
  {
    id: "e-brief-creative",
    source: "brief",
    target: "creative",
    markerEnd: { type: MarkerType.ArrowClosed, width: 14, height: 14, color: "#d3d1cb" },
  },
  {
    id: "e-creative-qa",
    source: "creative",
    target: "qa",
    markerEnd: { type: MarkerType.ArrowClosed, width: 14, height: 14, color: "#d3d1cb" },
  },
  {
    id: "e-qa-li3",
    source: "qa",
    target: "asset-li3",
    markerEnd: { type: MarkerType.ArrowClosed, width: 14, height: 14, color: "#d3d1cb" },
  },
  {
    id: "e-creative-email",
    source: "creative",
    target: "asset-email",
    markerEnd: { type: MarkerType.ArrowClosed, width: 14, height: 14, color: "#d3d1cb" },
  },
  {
    id: "e-creative-lp",
    source: "creative",
    target: "asset-lp",
    markerEnd: { type: MarkerType.ArrowClosed, width: 14, height: 14, color: "#d3d1cb" },
  },
  {
    id: "e-li3-agent",
    source: "asset-li3",
    target: "agent-compliance",
    animated: true,
    style: { stroke: "#1f6c9f" },
    markerEnd: { type: MarkerType.ArrowClosed, width: 14, height: 14, color: "#1f6c9f" },
  },
  {
    id: "e-li3-comment",
    source: "asset-li3",
    target: "comment-legal",
    markerEnd: { type: MarkerType.ArrowClosed, width: 14, height: 14, color: "#d3d1cb" },
  },
  {
    id: "e-li3-blocker",
    source: "asset-li3",
    target: "blocker-claim",
    style: { stroke: "#9f2f2d" },
    markerEnd: { type: MarkerType.ArrowClosed, width: 14, height: 14, color: "#9f2f2d" },
  },
  {
    id: "e-email-us",
    source: "asset-email",
    target: "market-us",
    markerEnd: { type: MarkerType.ArrowClosed, width: 14, height: 14, color: "#d3d1cb" },
  },
  {
    id: "e-lp-uk",
    source: "asset-lp",
    target: "market-uk",
    markerEnd: { type: MarkerType.ArrowClosed, width: 14, height: 14, color: "#d3d1cb" },
  },
  {
    id: "e-lp-de",
    source: "asset-lp",
    target: "market-de",
    markerEnd: { type: MarkerType.ArrowClosed, width: 14, height: 14, color: "#d3d1cb" },
  },
  {
    id: "e-de-agent",
    source: "market-de",
    target: "agent-l10n",
    animated: true,
    style: { stroke: "#956400" },
    markerEnd: { type: MarkerType.ArrowClosed, width: 14, height: 14, color: "#956400" },
  },
  {
    id: "e-de-blocker",
    source: "market-de",
    target: "blocker-de",
    style: { stroke: "#9f2f2d" },
    markerEnd: { type: MarkerType.ArrowClosed, width: 14, height: 14, color: "#9f2f2d" },
  },
  {
    id: "e-us-launch",
    source: "market-us",
    target: "launch",
    markerEnd: { type: MarkerType.ArrowClosed, width: 14, height: 14, color: "#d3d1cb" },
  },
  {
    id: "e-uk-launch",
    source: "market-uk",
    target: "launch",
    markerEnd: { type: MarkerType.ArrowClosed, width: 14, height: 14, color: "#d3d1cb" },
  },
  {
    id: "e-de-launch",
    source: "market-de",
    target: "launch",
    style: { strokeDasharray: "4 4" },
    markerEnd: { type: MarkerType.ArrowClosed, width: 14, height: 14, color: "#d3d1cb" },
  },
];
